### ISSUE TITLE
Setting does not save for the Templates or Scripts locations

### ISSUE THREAD

**Issue by Crazypedia** [willasm/vc-weather#12]
when updating the advanced settings to tell it where the Template and Script folders are, it does not save the location and always clears out the specified location, leading to template placeholders to fill with weather data from the last day they were edited.

in the screenshot below, the Template setting had been set to Templates and the Scripts setting had the Scripts folder selected. 

![image](https://github.com/user-attachments/assets/3525312c-6d71-4deb-b11a-351a5eafadaa)

**Comment by willasm** [comment]
Thanks for reporting this. I will have it fixed as soon as possible.

Thanks, William

**Comment by willasm** [comment]
Fixed in v0.3.0

Not sure how I missed that? It was a simple typo, was missing the last character of the settings name causing it to save to the first excludes folder setting.

Thanks for reporting this, William

**Comment by willasm** [comment]
Plugin has now been added to the community plugins list. BRAT plugin is no longer required to install/update the plugin.

Thanks for all the input, William
