### ISSUE TITLE
[FR] Wind direction abbreviation 'NE' instead of 'northeast'

### ISSUE THREAD

**Issue by Drakemoor** [willasm/vc-weather#13]
I like the plugin as it is, but it would be really nice if the wind directions were given instead of 'northeast' or 'south' or 'east south-east' wording, in 'NE', 'S', or 'ESE' and so on.  

That could save a lot of space giving the exact same information. 

Thank you for your consideration. ❤

**Comment by willasm** [comment]
This is done in version v0.3.1

The only difference in the macros is this for the long version `%winddirstr-today%` and for the short version use `%winddirstrshort-today%`. Thanks, that was something I wanted to add for quite a while now. It does save a lot of space in the output.

Thanks, William.

**Comment by Drakemoor** [comment]
Works great. I love it. 

Thank you. 🙇‍♂️

**Comment by willasm** [comment]
Plugin has now been added to the community plugins list. BRAT plugin is no longer required to install/update the plugin.

Thanks for all the input, William
