### ISSUE TITLE
Have to turn plug in on every time?

### ISSUE THREAD

**Issue by Cossackx** [willasm/vc-weather#15]
Wondering if this is an issue on my end...

Most times I start up Obsidian, this plug in is turned off and I have to turn it on manually. On mobile, I find it off even more consistently. I'm wondering if its the plugin, BRAT, or maybe sync. Anyone have this issue?

**Comment by willasm** [comment]
No one else has reported this and it works as expected for me. Are you saying it does this on both desktop and mobile? Plugins have no control over enabling/disabling plugins, that is all handled by Obsian. What OS are you using and what version of Obsidian? If you are using sync I would suspect that first. Try turnig sync off for a while and see if it continues to happen. I don't have sync so cannot test that myself.

**Comment by willasm** [comment]
Closing this issue as I am unable to reproduce this.

Plugin has now been added to the community plugins list. BRAT plugin is no longer required to install/update the plugin.

Thanks for all the input, William
