### ISSUE TITLE
can't enable plugin on mobile

### ISSUE THREAD

**Issue by htmljenn** [willasm/vc-weather#3]
Thank you so much for this update! 

I installed using BRAT with no issues, but on my mobile device I can't enable. Obsidian seems to think this is a desktop plugin only. 

This means I can't add my API key to get it working on my mobile device.

I'm testing on an iPad. 

And thanks AGAIN for doing this. I loved your OpenWeather plugin and used it everyday. And the Visual Crossing data is **so much nicer** even without the API.

**Comment by willasm** [comment]
At the moment it is not available on mobile. In order to get the plugin working quickly (before the old one stops working) I needed to make one call using fs which is not supported on mobile. As of now the plugin is complete as far as adding features goes so I will look into this right now and find a workaround for that one call so I can re-enable mobile support. I will let you know as soon as that iss done.

Thanks, William.

**Comment by willasm** [comment]
Added mobile support in v0.0.5

Can you please test this for me and let me know if it is working for you now?

Thanks, William.

**Comment by willasm** [comment]
@htmljenn Just curious, how long did it take to get your key emailed to you?
I had been considering swithching to this API for over half a year now so I requested my key a long time ago and can't recall how long it took to arrive. Just would like to know so I can add an approximate time frame for delivery in the readme file.

Thanks, William.

**Comment by htmljenn** [comment]
@willasm I haven't gotten my key mailed to me yet. I got it by going into my account settings and grabbing it from there. The steps:

1. Login to Visual Crossing
2. Click on the Account button in the top left
3. Under "Your details" I chose "Copy" from my Key. 

I pasted that in, in the plugin settings on my Mac and it began working beautifully. 

---

side note: the plugin is expanding the shortcut codes in files that are stored in the folder I listed my templates as being in. I'd really like it to just ignore the codes in a directory and ALL subdirectories under it (that is, that's what would work best for my setup) but having two directories to blacklist is helpful.

**Comment by htmljenn** [comment]
I realized I hadn't answered your first question. 

BRAT is not recognizing the update on my iPad. So while it's visible in my Community Plugins, I still cannot enable it there. 

All of my testing (above) was done on a Mac.

**Comment by willasm** [comment]
The default behavior should be to exclude all sub folders under your excluded folder. You may need to check your settings file (data.json) for the plugin (it is in the plugins directory) to verify it is correct.

Note: Quick tip regarding the plugins settings file. You can edit it manually if needed then restart Obsidian for the changes to take effect. To rebuild it you can just delete the file, but then you would have to re-enter everything. To avoid having to re-enter everything you can delete every line except the ones for your API key and the primary location (the first one) then make any change to the plugin settings in Obsidian to generate the missing keys in the data file. A good reason to do this is I have in fact made changes to some of the default template strings but you will never see these changes as they are already defined in the data.json file with the old keys. You would need to delete the old keys to have them replaced with the new ones.

Thanks, William.

**Comment by htmljenn** [comment]
GREAT! It's working fine. I realized the issue was on my side (I tend to push Obsidian past what it wants to do quickly....) But when I rebooted (three times!!) it is now working. It blocks the directories I want blocked and is updating my files exactly as I want it to. 

Thanks again for this.

**Comment by willasm** [comment]
Glad it is working for you. Thanks for the feedback.

**Comment by willasm** [comment]
@htmljenn and anyone else using this plugin on mobiles.

I have had to disable mobile support once again as my work around apparently is not valid on mobile. You can continue using v0.2.0 if you need it on mobile until I find a solution to this. Sorry but I needed to make the change in order for Obsidian to accept the plugin submission.

Thanks for your patience, William.

**Comment by htmljenn** [comment]
Thanks for letting me know. i've got it running on 0.2.0 for now on my mobile. 

Good luck getting it submitted. And thanks for working on this! It's working great for me. 

The only thing I notice is that if I don't edit a file that I've added it to with a template, the shortcuts don't expand. But since they expand as soon as I hit edit, it's not been a problem.

**Comment by willasm** [comment]
Sorry for not responding to this sooner but I have not been working on this until it gets approved for the community plugins list. It currently has passed all automated tests and just needs final approval from an Obsidian team member. That can take up to a month and it has been close to that now so it should be soon.

Just curious, do you have new files set to open in preview mode? The template will not expand in preview mode. That is just how Obsidian works, the file can not be edited while in preview mode. 

Thanks, William.

**Comment by htmljenn** [comment]
No worries. 

And thanks for the explanation. I do open in preview. And I have just been toggling edit mode on and off.

Thanks!

**Comment by willasm** [comment]
Just wanted to let you know I just uploaded an update. It removes the update every 5 minutes option as that will exceed your daily requests limit if 4 or more locations are set. Found this out the hard way, lol. It also sends notifications for returned status errors (see the change log for details). Had to add this as the plugin was just showing the last successful update information which meant I had no idea the error was occuring. I still need to have it stop showing the last successful updates data if this does occur, but at least it will send the notification now.

**Comment by ceccadroid** [comment]
Hi! Can you pleasehelp meabout əhete to find the 0.2.0 version and about how to install in on my mobile?
Thanks in advance

**Comment by willasm** [comment]
@ceccadroid You will need to use the [Brat](https://github.com/TfTHacker/obsidian42-brat) plugin to install it. Documentation can be found [here](https://tfthacker.com/BRAT).

If you need more help let me know, William.

**Comment by ceccadroid** [comment]
Thanks a lot. I'm using Brat both in my PC and my mobile. Since on mobile the plugin doesn't work I've read that I need to use version 0.2.0 (currently I'm on 0.2.3).
I need to know how to downgrade of anyway where I can find the old version and how can I install it on my mobile.
Thanks in advance for any help and for the prompt reply

28 ott 2024 22:58:21 William McKeever ***@***.***>:

**Comment by willasm** [comment]
In Brats settings there is an option button to `Add beta plugin with frozen version`. Click that and add the url `https://github.com/willasm/vc-weather` and on the first line and below that add `2.0.0` and that should work.

I will try adding mobile support again this week. Need to make several changes already to get it added to the community plugins list so will see what I can do while I'm doing that.

Thanks, William.

**Comment by willasm** [comment]
Good news to everyone posting in this issue. I have re-enabled mobile support in the latest release v0.2.4 If anyone has Brat set to freeze on version 0.2.0 you can remove that and let it update to the new version.

So long as the Obsidian team does not find any issues, it should be supported permanently.

Thanks William.
