### ISSUE TITLE
No Templates

### ISSUE THREAD

**Issue by techdixie** [willasm/vc-weather#6]
Hey! Did I install this wrong?  I grabbed my API, installed the repo via BRAT. However, console doesn't bring up anything and when I click insert template the list in empty. I'm rather new to Obsidian.  Thank you so much for your help and patience!

**Comment by willasm** [comment]
Did you get this figured out yet? You will need to go into the plugins settings and add your API key, set your primary location, and set an exclude folder (should be your templates folder) then re-start Obsidian.

If you need more information let me know, William.

**Comment by techdixie** [comment]
<img width="780" alt="Screenshot 2024-10-01 at 8 42 35 AM" src="https://github.com/user-attachments/assets/2f5031bf-1a8c-40cd-a1f6-3dea32e2a8a5">

I believe I did that.

**Comment by willasm** [comment]
You have an URL where your API key should be. This should be a string of 25 upper case letters and numbers. Visual crossing should have emailed this to you.

The rest looks good, William.

**Comment by techdixie** [comment]
Figured it out, wasn't emailed to me, but it was the number at the end of the link.  Works now, Thanks!
