### ISSUE TITLE
precipitation probability question

### ISSUE THREAD

**Issue by htmljenn** [willasm/vc-weather#7]
Hi, I'm using the `%precipprob%` and `%precipprob-in1day%` templates in my fields. And while the in1day one seems to be working correctly, the daily one only ever gives me 0% except for the day it was actually raining right at the moment I called the script. Then it gave me 100%. 

When I checked with the Visual Crossing weather data directly for today, it said the precipprob was 8, not 0. 

I"m wondering if `%precipprob%` is accidentally pointing to a more specific measure like current precipitation or precipitation cover, rather than the probability it will rain today. Or if I'm not understanding what that value represents.

**Comment by willasm** [comment]
Try using `%precipprobtoday%` instead. That will give you the pop for the whole day rather than what is happening right now.

**Comment by htmljenn** [comment]
That worked perfectly. Thanks!

**Comment by willasm** [comment]
Thank you for letting me know. The plugin is just waiting for final approval by Obsidian and should hopefully be added to the community plugins soon.

Thanks, William.
