### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by DragonN129495** [willasm/vc-weather#9]
My problem is that the plugin is not included in the plugin list. I tried to install it via BRAT and it was included, but no settings were applied, and if I turn it off in the list, it will not be included back. I had this error "Failed to load plugin "visual-crossing-weather"". I installed the plugin in new vault and this error appears there too.  ![image](https://github.com/user-attachments/assets/47165295-6b1b-4f4f-9d95-ed80113dbc97) 
![image](https://github.com/user-attachments/assets/707d4563-f1f1-43d8-9d1c-505836e40545)

**Comment by willasm** [comment]
Did you ever manage to get this working? I am going to close this as I have not heard back from you in 2 weeks now.

If you still are having an issue with the plugin, please let me know, William.
